<?php

namespace ModulaR\modularBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends EntityRepository
{
	public function findAllArray(){
		$data = $this->findAll();
        $out = [];
        foreach ($data as $obj) {
            $out[] = $obj->getVars();
        }
        return $out;
	}

	public function findArray($id){
		$data = $this->find($id);
		if (!$data) throw $this->createNotFoundException('No data found with the id : ' . $id);
        return $data->getVars();
	}
}
