<?php

namespace ModulaR\modularBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostModuleRepository extends DataModuleRepository
{
}
