<?php

namespace ModulaR\modularBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserModuleRepository extends ModuleRepository
{
}
