name 	: Data
extends : Module

labels :
    title 	: { en : 'Data', fr : 'Data' }
    name 	: { en : 'data', fr : 'data' }
    noData  : 
        en : 'No data found'
        fr : 'Aucune donnée trouvée'
    fields :
        en :
            title 	: 'title'
            slug 	: 'slug'
        fr :
            title 	: 'titre'
            slug 	: 'identifiant'

icon : 'ion-gear-b'