name 	: Data
extends : Module

labels :
    title 	: { en : 'Data', fr : 'Data' }
    name 	: { en : 'data', fr : 'data' }
    noData  : 
        en : 'No data found'
        fr : 'Aucune donnée trouvée'
    fields :
        en :
            created 	: 'created'
            updated 	: 'last update'

        fr :
            created 	: 'création'
            updated 	: 'dernière mise à jour'
