name : User
extends : Data

labels :
    title 	: { en : 'Users', fr : 'Utilisateurs' }
    name 	: { en : 'users', fr : 'users' }
    noData  : 
        en : 'No users found'
        fr : 'Aucun utilisateurs trouvé'
    fields :
        en :
            email : email
            role : role
            firstname : firstname
            lastname : lastname
            bio : biographie
        fr :
            email : email
            role : role
            firstname : prénom
            lastname : nom
            bio : biographie

icon : 'ion-person-stalker'

form : true